{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedLists #-}

module Config.ForcedExecutables ( forcedExectableNames ) where

import MyCabal

import Data.Set ( Set )

forcedExectableNames :: Set PackageName
forcedExectableNames =
  [ "Agda"
  , "BNFC"
  , "BlogLiterately"
  , "HaRe"
  , "HaXml"
  , "ShellCheck"
  , "alex"
  , "apply-refact"
  , "asciidiagram"
  , "bustle"
  , "c2hs"
  , "cab"
  , "cabal-install"
  , "cabal-plan"
  , "cabal-rpm"
  , "cabal2nix"
  , "cabal2spec"
  , "clash-ghc"
  , "codex"
  , "cpphs"
  , "cryptol"
  , "darcs"
  , "derive"
  , "dhall-json"
  , "dhall-yaml"
  , "diagrams-haddock"
  , "dixi"
  , "doctest"
  , "doctest-discover"
  , "find-clumpiness"
  , "ghc-imported-from"
  , "ghc-mod"
  , "ghcid"
  , "git-annex"
  , "gtk2hs-buildtools"
  , "hackage-mirror"
  , "hackmanager"
  , "hadolint"
  , "handwriting"
  , "hapistrano"
  , "happy"
  , "haskintex"
  , "hdevtools"
  , "hdocs"
  , "highlighting-kate"
  , "hindent"
  , "hledger"
  , "hledger-web"
  , "hlint"
  , "holy-project"
  , "hoogle"
  , "hpack"
  , "hpc-coveralls"
  , "hscolour"
  , "hsdev"
  , "hspec-discover"
  , "hspec-setup"
  , "ide-backend"
  , "idris"
  , "keter"
  , "leksah-server"
  , "lhs2tex"
  , "liquidhaskell"
  , "markdown-unlit"
  , "microformats2-parser"
  , "misfortune"
  , "modify-fasta"
  , "msi-kb-backlit"
  , "omnifmt"
  , "osdkeys"
  , "pointfree"
  , "pointful"
  , "postgresql-schema"
  , "purescript"
  , "quickbench"
  , "shake"
  , "stack"
  , "stack-run-auto"
  , "stackage-curator"
  , "stylish-cabal"
  , "stylish-haskell"
  , "texmath"
  , "titlecase"
  , "werewolf"
  , "wordpass"
  , "xmobar"
  , "xmonad"
  , "yi"
  ]
