{-# LANGUAGE OverloadedLists #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}

module Config.Ghc810x ( ghc810x ) where

import Config.ForcedExecutables
import Oracle.Hackage ( )
import Types
import MyCabal

import Control.Monad
import qualified Data.List as List
import qualified Data.Map as Map
import Data.Map.Strict ( fromList, toList )
import Data.Maybe
import qualified Data.Set as Set
import Development.Shake

ghc810x :: Action PackageSetConfig
ghc810x = do
  let compiler = "ghc-8.10.7"
      flagAssignments = fromList (readFlagAssignents flagList)
      forcedExectables = forcedExectableNames
      corePackages = ghcCorePackages
  packageSet <- fromList <$>
                  forM (toList constraintList) (\(pn,vr) ->
                    (,) pn <$> askOracle (PackageVersionConstraint pn vr))
  checkConsistency (PackageSetConfig {..})

-- targetPackages :: ConstraintSet
-- targetPackages   = [ "pandoc-cli"
--                    ]
--
-- resolveConstraints :: String
-- resolveConstraints = unwords ["cabal", "install", "--dry-run", "--minimize-conflict-set", constraints, flags, pkgs]
--   where
--     pkgs = unwords (display <$> Map.keys targetPackages)
--     constraints = "--constraint=" <> List.intercalate " --constraint=" (show <$> environment)
--     environment = display . uncurry PackageVersionConstraint <$> toList targetPackages
--     flags = unwords [ "--constraint=" <> show (unwords [unPackageName pn, flags'])
--                     | pn <- Map.keys targetPackages
--                     , Just flags' <- [lookup (unPackageName pn) flagList]
--                     ]

constraintList :: ConstraintSet
constraintList = [ "adjunctions ^>= 4.4"
                 , "aeson-yaml ^>= 1.1.0.1"
                 , "ansi-wl-pprint ^>= 0.6.9"
                 , "ascii-progress ^>= 0.3.3.0"
                 , "attoparsec-iso8601 ^>= 1.0.2.1"
                 , "aws ^>= 0.22"
                 , "base64-bytestring-type ^>= 1.0.1"
                 , "bech32 ^>= 1.1.2"
                 , "binary-orphans ^>= 1.0.2"
                 , "brick ^>= 0.67"
                 , "cassava-megaparsec ^>= 2.0.4"
                 , "cborg ^>= 0.2.6.0"
                 , "cborg-json ^>= 0.2.3.0"
                 , "concurrent-output ^>= 1.10.15"
                 , "criterion ^>= 1.5.13.0"
                 , "cryptohash ^>= 0.11.9"
                 , "cryptohash-conduit ^>= 0.1.1"
                 , "cryptonite-conduit ^>= 0.2.2"
                 , "DAV ^>= 1.3.4"
                 , "dbus ^>= 1.2.22"
                 , "dense-linear-algebra ^>= 0.1.0.0"
                 , "dhall ^>= 1.40.2"
                 , "distribution-opensuse ^>= 1.1.3"
                 , "dns ^>= 4.0.1"
                 , "either ^>= 5.0.1.1"
                 , "ekg ^>= 0.4.0.15"
                 , "ekg-json ^>= 0.1.0.6"
                 , "fdo-notify ^>= 0.3.1"
                 , "feed ^>= 1.3.2.0"
                 , "foldl ^>= 1.4.12"
                 , "foundation ^>= 0.0.28"
                 , "free ^>= 5.1.7"
                 , "fsnotify ^>= 0.3.0.1"
                 , "generic-deriving ^>= 1.14.1"
                 , "generic-lens ^>= 2.2.1.0"
                 , "ghcid ^>= 0.8.7"
                 , "git-annex"
                 , "git-lfs ^>= 1.2.0"
                 , "hashtables ^>= 1.2.4.2"
                 , "hedgehog ^>= 1.1.1"
                 , "hedgehog-quickcheck ^>= 0.1.1"
                 , "hledger ^>= 1.26.1"
                 , "hledger-lib ^>= 1.26.1"
                 , "HsYAML-aeson ^>= 0.2.0.1"
                 , "http-client-restricted ^>= 0.0.5"
                 , "infer-license ^>= 0.2.0"
                 , "invariant ^>= 0.5.5"
                 , "io-streams ^>= 1.5.2.1"
                 , "io-streams-haproxy ^>= 1.0.1.0"
                 , "kan-extensions ^>= 5.2.3"
                 , "katip ^>= 0.8.7.0"
                 , "lens ^>= 5.1"
                 , "lens-aeson ^>= 1.1.3"
                 , "libsystemd-journal ^>= 1.4.5"
                 , "lifted-async ^>= 0.10.2.2"
                 , "ListLike ^>= 4.7.6"
                 , "microlens-platform ^>= 0.4.2.1"
                 , "microlens-th ^>= 0.4.3.10"
                 , "microstache ^>= 1.0.2"
                 , "monad-logger ^>= 0.3.36"
                 , "MonadRandom ^>= 0.5.3"
                 , "moo ^>= 1.2"
                 , "optics ^>= 0.4"
                 , "optics-extra ^>= 0.4"
                 , "optics-th ^>= 0.4"
                 , "optparse-generic ^>= 1.4.7"
                 , "persistent ^>= 2.13.3.0"
                 , "persistent-sqlite ^>= 2.13.1.0"
                 , "pipes-safe ^>= 2.3.3"
                 , "postgresql-simple ^>= 0.6.4"
                 , "process-extras ^>= 0.7.4"
                 , "profunctors ^>= 5.6.2"
                 , "protolude ^>= 0.3.0"
                 , "quickcheck-instances ^>= 0.3.27"
                 , "random-shuffle ^>= 0.0.4"
                 , "recursion-schemes ^>= 5.2.2.2"
                 , "reducers ^>= 3.12.4"
                 , "rio-orphans ^>= 0.1.2.0"
                 , "serialise ^>= 0.2.4.0"
                 , "servant-client ^>= 0.19"
                 , "servant-client-core ^>= 0.19"
                 , "shelltestrunner ^>= 1.9"
                 , "shelly ^>= 1.10.0"
                 , "smtp-mail ^>= 0.3.0.0"
                 , "snap-core ^>= 1.0.4.2"
                 , "snap-server ^>= 1.1.2.0"
                 , "statistics ^>= 0.16.0.1"
                 , "statistics-linreg ^>= 0.3"
                 , "tasty-hedgehog ^>= 1.1.0.0"
                 , "tdigest ^>= 0.2.1.1"
                 , "test-framework ^>= 0.8.2.0"
                 , "test-framework-hunit ^>= 0.3.0.2"
                 , "text-metrics ^>= 0.3.2"
                 , "th-expand-syns ^>= 0.4.9.0"
                 , "th-orphans ^>= 0.13.12"
                 , "th-reify-many ^>= 0.1.10"
                 , "th-utilities ^>= 0.2.4.3"
                 , "threepenny-gui ^>= 0.9.1.0"
                 , "topograph ^>= 1.0.0.1"
                 , "tree-diff ^>= 0.2.1.1"
                 , "turtle ^>= 1.5.24"
                 , "Unique ^>= 0.4.7.9"
                 , "vector-binary-instances ^>= 0.2.5.2"
                 , "vector-builder ^>= 0.3.8.3"
                 , "vector-th-unbox ^>= 0.2.2"
                 , "vty ^>= 5.33"
                 , "warp-tls ^>= 3.3.2"
                 , "websockets-snap ^>= 0.10.3.1"
                 , "weeder ^>= 2.2.0"
                 , "wl-pprint-text ^>= 1.2.0.2"
                 , "wreq ^>= 0.5.3.3"
                 , "yesod ^>= 1.6.2"
                 , "yesod-core ^>= 1.6.21.0"
                 , "yesod-form ^>= 1.7.0"
                 , "yesod-persistent ^>= 1.6.0.7"
                 , "yesod-static ^>= 1.6.1.0"
                 , "zip ^>= 1.7.2"

                 -- new dependencies
                 , "connection >= 0.2.5"
                 , "x509 >=1.5"
                 , "x509-store >=1.5"
                 , "x509-system >=1.5"
                 , "x509-validation >=1.5"
                 , "cryptonite"
                 , "HsYAML ^>=0.2.0"
                 ]

flagList :: [(String,String)]
flagList =
  [ ("cabal-plan",                     "exe")

    -- Don't build hardware-specific optimizations into the binary based on what the
    -- build machine supports or doesn't support.
  , ("cryptonite",                     "-support_aesni -support_rdrand -support_sse")

    -- Don't use the bundled sqlite3 library.
  , ("direct-sqlite",                  "systemlib")

    -- dont optimize happy with happy ( dep on same package ..)
  , ("happy",                          "-bootstrap")

    -- Build the standalone executable and prefer pcre-light, which uses the system
    -- library rather than a bundled copy.
  , ("highlighting-kate",              "executable pcre-light")

    -- Don't use the bundled sass library.
  , ("hlibsass",                       "externalLibsass")

    -- Use the bundled lua library. People expect this package to provide LUA
    -- 5.3, but we don't have that yet in openSUSE.
  , ("hslua",                          "-system-lua")

    -- Allow compilation without having Nix installed.
  , ("nix-paths",                      "allow-relative-paths")

    -- Build the standalone executable.
  , ("texmath",                        "executable")

    -- Enable almost all extensions.
  , ("xmobar",                         "all_extensions")

    -- Enable additional features
  , ("idris",                          "ffi gmp")

    -- Disable dependencies we don't have.
  , ("invertible",                     "-hlist -piso")

    -- Use the system sqlite library rather than the bundled one.
  , ("persistent-sqlite",              "systemlib")

    -- Make sure we're building with the test suite enabled.
  , ("git-annex",                      "testsuite")

    -- Compile against the system library, not the one bundled in the Haskell
    -- source tarball.
  , ("cmark",                          "pkgconfig")

    -- Fix build with modern compilers.
  , ("cassava",                        "-bytestring--lt-0_10_4")

    -- Prefer the system's library over the bundled one.
  , ("libyaml",                        "system-libyaml")

    -- Configure a production-like build environment.
  , ("stack",                          "hide-dependency-versions disable-git-info supported-build")

    -- The command-line utility pulls in other dependencies.
  , ("aeson-pretty",                   "lib-only")

    -- Build the standalone executable for skylighting.
  , ("skylighting",                    "executable")

    -- Compile against system zstd library
  , ("zstd",                           "-standalone")

    -- Static linking breaks the build.
  , ("hadolint",                       "-static")

    -- Enable LUA support.
  , ("pandoc-cli",                     "+lua +server")
  ]

readFlagAssignents :: [(String,String)] -> [(PackageName,FlagAssignment)]
readFlagAssignents xs = [ (fromJust (simpleParse name), readFlagList (words assignments)) | (name,assignments) <- xs ]

readFlagList :: [String] -> FlagAssignment
readFlagList = mkFlagAssignment . map (tagWithValue . noMinusF)
  where
    tagWithValue ('-':fname) = (mkFlagName (lowercase fname), False)
    tagWithValue fname       = (mkFlagName (lowercase fname), True)

    noMinusF :: String -> String
    noMinusF ('-':'f':_) = error "don't use '-f' in flag assignments; just use the flag's name"
    noMinusF x           = x

ghcCorePackages :: PackageSet
ghcCorePackages = [ "array-0.5.4.0"
                  , "base-4.14.3.0"
                  , "binary-0.8.8.0"
                  , "bytestring-0.10.12.0"
                  , "Cabal-3.2.1.0"
                  , "containers-0.6.5.1"
                  , "deepseq-1.4.4.0"
                  , "directory-1.3.6.0"
                  , "exceptions-0.10.4"
                  , "filepath-1.4.2.1"
                  , "ghc-8.10.3"
                  , "ghc-boot-8.10.7"
                  , "ghc-boot-th-8.10.7"
                  , "ghc-compact-0.1.0.0"
                  , "ghc-heap-8.10.7"
                  , "ghc-prim-0.6.1"
                  , "ghci-8.10.7"
                  , "haskeline-0.8.2"
                  , "hpc-0.6.1.0"
                  , "hsc2hs-0.68.7"
                  , "integer-gmp-1.0.3.0"
                  , "libiserv-8.10.7"
                  , "mtl-2.2.2"
                  , "parsec-3.1.14.0"
                  , "pretty-1.1.3.6"
                  , "process-1.6.13.2"
                  , "rts-1.0"
                  , "stm-2.5.0.1"
                  , "template-haskell-2.16.0.0"
                  , "terminfo-0.4.1.4"
                  , "text-1.2.4.1"
                  , "time-1.9.3"
                  , "transformers-0.5.6.2"
                  , "unix-2.7.2.2"
                  , "xhtml-3000.2.2.1"

                  , "attoparsec-aeson-2.1"

                  -- packages we inherit from SLE-15-SP5
                  , "aeson-2.1.2.1"
                  , "aeson-pretty-0.8.10"
                  , "alex-3.4.0.1"
                  , "ansi-terminal-1.0"
                  , "ansi-terminal-types-0.11.5"
                  , "appar-0.1.8"
                  , "asn1-encoding-0.9.6"
                  , "asn1-parse-0.9.5"
                  , "asn1-types-0.3.4"
                  , "assoc-1.1"
                  , "async-2.2.5"
                  , "attoparsec-0.14.4"
                  , "auto-update-0.1.6"
                  , "base-compat-0.13.1"
                  , "base-compat-batteries-0.13.1"
                  , "base-orphans-0.9.1"
                  , "base-unicode-symbols-0.2.4.2"
                  , "base16-bytestring-1.0.2.0"
                  , "base64-0.4.2.4"
                  , "base64-bytestring-1.2.1.0"
                  , "basement-0.0.16"
                  , "bifunctors-5.6.1"
                  , "bitvec-1.1.5.0"
                  , "blaze-builder-0.4.2.3"
                  , "blaze-html-0.9.1.2"
                  , "blaze-markup-0.8.3.0"
                  , "boring-0.2.1"
                  , "bsb-http-chunked-0.0.0.4"
                  , "byteorder-1.0.4"
                  , "cabal-doctest-1.0.9"
                  , "call-stack-0.4.0"
                  , "case-insensitive-1.2.1.0"
                  , "cassava-0.5.3.0"
                  , "cereal-0.5.8.3"
                  , "citeproc-0.8.1"
                  , "colour-2.3.6"
                  , "commonmark-0.2.4"
                  , "commonmark-extensions-0.2.4"
                  , "commonmark-pandoc-0.2.1.3"
                  , "comonad-5.0.8"
                  , "conduit-1.3.5"
                  , "conduit-extra-1.3.6"
                  , "constraints-0.14"
                  , "contravariant-1.5.5"
                  , "cookie-0.4.6"
                  , "crypton-0.34"
                  , "crypton-connection-0.3.1"
                  , "crypton-x509-1.7.6"
                  , "crypton-x509-store-1.6.9"
                  , "crypton-x509-system-1.6.7"
                  , "crypton-x509-validation-1.6.12"
                  , "data-array-byte-0.1.0.1"
                  , "data-default-0.7.1.1"
                  , "data-default-class-0.1.2.0"
                  , "data-default-instances-containers-0.0.1"
                  , "data-default-instances-dlist-0.0.1"
                  , "data-default-instances-old-locale-0.0.1"
                  , "data-fix-0.3.2"
                  , "dec-0.0.5"
                  , "digest-0.0.1.3"
                  , "digits-0.3.1"
                  , "distributive-0.6.2.1"
                  , "dlist-1.0"
                  , "doclayout-0.4.0.1"
                  , "doctemplates-0.11"
                  , "easy-file-0.2.5"
                  , "emojis-0.1.3"
                  , "fast-logger-3.2.2"
                  , "file-embed-0.0.15.0"
                  , "foldable1-classes-compat-0.1"
                  , "generically-0.1.1"
                  , "Glob-0.10.2"
                  , "gridtables-0.1.0.0"
                  , "haddock-library-1.11.0"
                  , "hashable-1.4.3.0"
                  , "haskell-lexer-1.1.1"
                  , "hourglass-0.2.12"
                  , "hslua-2.3.0"
                  , "hslua-aeson-2.3.0.1"
                  , "hslua-classes-2.3.0"
                  , "hslua-cli-1.4.1"
                  , "hslua-core-2.3.1"
                  , "hslua-list-1.1.1"
                  , "hslua-marshalling-2.3.0"
                  , "hslua-module-doclayout-1.1.0"
                  , "hslua-module-path-1.1.0"
                  , "hslua-module-system-1.1.0.1"
                  , "hslua-module-text-1.1.0.1"
                  , "hslua-module-version-1.1.0"
                  , "hslua-module-zip-1.1.0"
                  , "hslua-objectorientation-2.3.0"
                  , "hslua-packaging-2.3.0"
                  , "hslua-repl-0.1.1"
                  , "hslua-typing-0.1.0"
                  , "http-api-data-0.6"
                  , "http-client-0.7.15"
                  , "http-client-tls-0.3.6.3"
                  , "http-date-0.0.11"
                  , "http-media-0.8.1.1"
                  , "http-types-0.12.4"
                  , "http2-5.0.0"
                  , "HUnit-1.6.2.0"
                  , "indexed-traversable-0.1.3"
                  , "indexed-traversable-instances-0.1.1.2"
                  , "integer-conversion-0.1.0.1"
                  , "integer-logarithms-1.0.3.1"
                  , "iproute-1.7.12"
                  , "ipynb-0.2"
                  , "isocline-1.0.9"
                  , "jira-wiki-markup-1.5.1"
                  , "JuicyPixels-3.3.8"
                  , "libyaml-0.1.2"
                  , "lpeg-1.0.4"
                  , "lua-2.3.1"
                  , "memory-0.18.0"
                  , "mime-types-0.1.2.0"
                  , "mmorph-1.2.0"
                  , "monad-control-1.0.3.1"
                  , "mono-traversable-1.0.15.3"
                  , "network-3.1.4.0"
                  , "network-byte-order-0.1.7"
                  , "network-control-0.0.2"
                  , "network-uri-2.6.4.2"
                  , "old-locale-1.0.0.7"
                  , "old-time-1.1.0.3"
                  , "OneTuple-0.4.1.1"
                  , "Only-0.1"
                  , "optparse-applicative-0.18.1.0"
                  , "ordered-containers-0.2.3"
                  , "pandoc-3.1.9"
                  , "pandoc-cli-0.1.1.1"
                  , "pandoc-lua-engine-0.2.1.2"
                  , "pandoc-lua-marshal-0.2.2"
                  , "pandoc-server-0.1.0.3"
                  , "pandoc-types-1.23.1"
                  , "pem-0.2.4"
                  , "pretty-show-1.10"
                  , "prettyprinter-1.7.1"
                  , "prettyprinter-ansi-terminal-1.1.3"
                  , "primitive-0.8.0.0"
                  , "psqueues-0.2.8.0"
                  , "QuickCheck-2.14.3"
                  , "random-1.2.1.1"
                  , "recv-0.1.0"
                  , "regex-base-0.94.0.2"
                  , "regex-tdfa-1.3.2.2"
                  , "resourcet-1.3.0"
                  , "safe-0.3.19"
                  , "safe-exceptions-0.1.7.4"
                  , "scientific-0.3.7.0"
                  , "semialign-1.3"
                  , "semigroupoids-6.0.0.1"
                  , "servant-0.20.1"
                  , "servant-server-0.20"
                  , "SHA-1.6.4.4"
                  , "simple-sendfile-0.2.32"
                  , "singleton-bool-0.1.7"
                  , "skylighting-0.14.1"
                  , "skylighting-core-0.14.1"
                  , "skylighting-format-ansi-0.1"
                  , "skylighting-format-blaze-html-0.1.1.1"
                  , "skylighting-format-context-0.1.0.2"
                  , "skylighting-format-latex-0.1"
                  , "socks-0.6.1"
                  , "some-1.0.6"
                  , "sop-core-0.5.0.2"
                  , "split-0.2.4"
                  , "splitmix-0.1.0.5"
                  , "StateVar-1.2.2"
                  , "streaming-commons-0.2.2.6"
                  , "strict-0.5"
                  , "string-conversions-0.4.0.1"
                  , "syb-0.7.2.4"
                  , "tagged-0.8.8"
                  , "tagsoup-0.14.8"
                  , "temporary-1.3"
                  , "texmath-0.12.8.4"
                  , "text-conversions-0.3.1.1"
                  , "text-iso8601-0.1"
                  , "text-short-0.1.5"
                  , "th-abstraction-0.5.0.0"
                  , "th-compat-0.1.4"
                  , "th-lift-0.8.4"
                  , "th-lift-instances-0.1.20"
                  , "these-1.2"
                  , "time-compat-1.9.6.1"
                  , "time-manager-0.0.1"
                  , "tls-1.9.0"
                  , "toml-parser-1.3.1.0"
                  , "transformers-base-0.4.6"
                  , "transformers-compat-0.7.2"
                  , "type-equality-1"
                  , "typed-process-0.2.11.1"
                  , "typst-0.3.2.1"
                  , "typst-symbols-0.1.4"
                  , "unicode-collation-0.1.3.5"
                  , "unicode-data-0.4.0.1"
                  , "unicode-transforms-0.4.0.1"
                  , "uniplate-1.6.13"
                  , "unix-compat-0.7.1"
                  , "unix-time-0.4.11"
                  , "unliftio-0.2.25.0"
                  , "unliftio-core-0.2.1.0"
                  , "unordered-containers-0.2.19.1"
                  , "utf8-string-1.0.2"
                  , "uuid-types-1.0.5.1"
                  , "vault-0.3.1.5"
                  , "vector-0.13.1.0"
                  , "vector-algorithms-0.9.0.1"
                  , "vector-stream-0.1.0.0"
                  , "wai-3.2.3"
                  , "wai-app-static-3.1.8"
                  , "wai-cors-0.2.7"
                  , "wai-extra-3.1.13.0"
                  , "wai-logger-2.4.0"
                  , "warp-3.3.31"
                  , "witherable-0.4.2"
                  , "word8-0.1.3"
                  , "xml-1.3.14"
                  , "xml-conduit-1.9.1.3"
                  , "xml-types-0.3.8"
                  , "yaml-0.11.11.2"
                  , "zip-archive-0.4.3"
                  , "zlib-0.6.3.0"

                  -- packages in Leap 15.6 that still build okay
                  , "abstract-deque-0.3"
                  , "abstract-par-0.3.3"
                  , "algebraic-graphs-0.6"
                  , "alsa-core-0.5.0.1"
                  , "alsa-mixer-0.3.0"
                  , "annotated-wl-pprint-0.7.0"
                  , "ap-normalize-0.1.0.1"
                  , "async-timer-0.2.0.0"
                  , "atomic-primops-0.8.4"
                  , "atomic-write-0.2.0.7"
                  , "authenticate-oauth-1.7"
                  , "barbies-2.0.3.1"
                  , "base-noprelude-4.13.0.0"
                  , "base-prelude-1.4"
                  , "base58-bytestring-0.1.0"
                  , "bech32-th-1.1.1"
                  , "bencode-0.6.1.1"
                  , "bento-0.1.0"
                  , "bimap-0.4.0"
                  , "bindings-DSL-1.0.25"
                  , "bindings-uname-0.1"
                  , "bitarray-0.0.1.1"
                  , "bitmap-0.0.2"
                  , "bloomfilter-2.0.1.0"
                  , "boxes-0.1.5"
                  , "byteable-0.1.1"
                  , "bytestring-builder-0.10.8.2.0"
                  , "bzlib-conduit-0.3.0.2"
                  , "Cabal-syntax-3.6.0.0"
                  , "canonical-json-0.6.0.0"
                  , "casing-0.1.4.1"
                  , "charset-0.3.9"
                  , "choice-0.2.1"
                  , "cipher-aes-0.2.11"
                  , "clay-0.13.3"
                  , "clientsession-0.9.1.2"
                  , "clock-0.8.3"
                  , "cmark-gfm-0.2.2"
                  , "cmdargs-0.10.21"
                  , "code-page-0.2.1"
                  , "concurrency-1.11.0.2"
                  , "conduit-combinators-1.3.0"
                  , "conduit-zstd-0.0.2.0"
                  , "config-ini-0.2.4.0"
                  , "continued-fractions-0.9.1.1"
                  , "control-monad-free-0.6.2"
                  , "converge-0.1.0.1"
                  , "cprng-aes-0.6.1"
                  , "criterion-measurement-0.1.3.0"
                  , "crypto-api-0.13.3"
                  , "crypto-cipher-types-0.0.9"
                  , "crypto-pubkey-types-0.4.3"
                  , "crypto-random-0.0.9"
                  , "cryptohash-md5-0.11.101.0"
                  , "cryptohash-sha1-0.11.101.0"
                  , "cryptohash-sha256-0.11.102.1"
                  , "css-text-0.1.3.0"
                  , "csv-0.1.2"
                  , "data-clist-0.1.2.3"
                  , "Decimal-0.5.2"
                  , "dependent-sum-0.4"
                  , "Diff-0.4.1"
                  , "disk-free-space-0.1.0.1"
                  , "dotgen-0.4.3"
                  , "double-conversion-2.0.4.1"
                  , "echo-0.1.4"
                  , "ed25519-0.0.5.0"
                  , "edit-distance-0.2.2.1"
                  , "ekg-core-0.1.1.7"
                  , "email-validate-2.3.2.15"
                  , "enclosed-exceptions-1.0.3"
                  , "entropy-0.4.1.7"
                  , "erf-2.0.0.0"
                  , "errors-2.3.0"
                  , "extensible-exceptions-0.1.1.4"
                  , "extra-1.7.9"
                  , "fail-4.9.0.0"
                  , "fgl-5.7.0.3"
                  , "filelock-0.1.1.5"
                  , "filemanip-0.3.6.3"
                  , "filepath-bytestring-1.4.2.1.9"
                  , "filepattern-0.1.2"
                  , "filtrable-0.1.6.0"
                  , "fingertree-0.1.5.0"
                  , "flow-1.0.7"
                  , "fmlist-0.9.4"
                  , "fmt-0.6.3.0"
                  , "formatting-7.1.3"
                  , "gamma-0.9.0.2"
                  , "generic-data-0.9.2.1"
                  , "generic-lens-core-2.2.1.0"
                  , "generic-monoid-0.1.0.1"
                  , "generic-random-1.5.0.1"
                  , "ghc-byteorder-4.11.0.0.10"
                  , "ghc-lib-parser-ex-8.10.0.19"
                  , "ghc-paths-0.1.0.12"
                  , "githash-0.1.6.2"
                  , "gitrev-1.3.1"
                  , "gray-code-0.3.1"
                  , "groups-0.5.3"
                  , "hackage-security-0.6.2.0"
                  , "half-0.3.1"
                  , "heaps-0.4"
                  , "hedgehog-corpus-0.2.0"
                  , "hi-file-parser-0.1.2.0"
                  , "hinotify-0.4.1"
                  , "hjsmin-0.2.0.4"
                  , "hostname-1.0"
                  , "hs-bibutils-6.10.0.0"
                  , "hsemail-2.2.1"
                  , "hslogger-1.3.1.0"
                  , "hspec-2.9.4"
                  , "hspec-core-2.9.4"
                  , "hspec-expectations-0.8.2"
                  , "hspec-golden-aeson-0.9.0.0"
                  , "hspec-smallcheck-0.5.2"
                  , "hsyslog-5.0.2"
                  , "html-1.0.1.2"
                  , "HTTP-4000.3.16"
                  , "http-conduit-2.3.8"
                  , "hxt-9.3.1.22"
                  , "hxt-charproperties-9.5.0.0"
                  , "hxt-regex-xmlschema-9.2.0.7"
                  , "hxt-unicode-9.0.2.4"
                  , "IfElse-0.85"
                  , "indexed-profunctors-0.1.1"
                  , "intern-0.9.4"
                  , "iso8601-time-0.1.5"
                  , "iwlib-0.1.0"
                  , "js-chart-2.9.4.1"
                  , "js-dgtable-0.5.2"
                  , "js-flot-0.8.3"
                  , "js-jquery-3.3.1"
                  , "language-c-0.9.0.1"
                  , "language-javascript-0.7.1.0"
                  , "largeword-1.2.5"
                  , "lens-family-core-2.1.0"
                  , "libmpd-0.10.0.0"
                  , "libxml-sax-0.7.5"
                  , "lift-type-0.1.0.1"
                  , "lifted-base-0.2.3.12"
                  , "logict-0.7.1.0"
                  , "loop-0.3.0"
                  , "lucid-2.11.0"
                  , "lukko-0.1.1.3"
                  , "magic-1.1"
                  , "managed-1.0.9"
                  , "math-functions-0.3.4.2"
                  , "megaparsec-9.2.0"
                  , "mersenne-random-pure64-0.2.2.0"
                  , "microlens-0.4.12.0"
                  , "microlens-ghc-0.4.13.1"
                  , "microlens-mtl-0.2.0.1"
                  , "mime-mail-0.5.1"
                  , "mintty-0.1.3"
                  , "monad-loops-0.4.3"
                  , "monad-par-0.3.5"
                  , "monad-par-extras-0.3.3"
                  , "monadloc-0.7.1"
                  , "mountpoints-1.0.2"
                  , "mtl-compat-0.2.2"
                  , "mustache-2.4.1"
                  , "mwc-random-0.15.0.2"
                  , "neat-interpolation-0.5.1.3"
                  , "netlink-1.1.1.0"
                  , "network-bsd-2.8.1.0"
                  , "network-info-0.2.1"
                  , "network-multicast-0.3.2"
                  , "nothunks-0.1.3"
                  , "OddWord-1.0.2.0"
                  , "open-browser-0.2.1.0"
                  , "optics-core-0.4"
                  , "optional-args-1.0.2"
                  , "optparse-simple-0.1.1.4"
                  , "parallel-3.2.2.0"
                  , "parsec-class-1.0.0.0"
                  , "parsec-numbers-0.1.0"
                  , "parser-combinators-1.3.0"
                  , "parsers-0.12.10"
                  , "partial-order-0.2.0.0"
                  , "path-0.9.2"
                  , "path-io-1.7.0"
                  , "path-pieces-0.2.1"
                  , "persistent-template-2.12.0.0"
                  , "pipes-4.3.16"
                  , "polyparse-1.13"
                  , "postgresql-libpq-0.9.4.3"
                  , "pretty-class-1.0.1.1"
                  , "pretty-hex-1.1"
                  , "pretty-simple-4.0.0.0"
                  , "prettyclass-1.0.0.0"
                  , "prometheus-2.2.3"
                  , "quickcheck-arbitrary-adt-0.3.1.0"
                  , "quickcheck-io-0.2.0"
                  , "quiet-0.2"
                  , "readable-0.3.1"
                  , "refact-0.3.0.2"
                  , "reflection-2.1.6"
                  , "regex-applicative-0.3.4"
                  , "regex-applicative-text-0.1.0.1"
                  , "regex-compat-0.95.2.1"
                  , "regex-pcre-builtin-0.95.2.3.8.44"
                  , "regex-posix-0.96.0.1"
                  , "reinterpret-cast-0.1.0"
                  , "repline-0.4.0.0"
                  , "resolv-0.1.2.0"
                  , "resource-pool-0.2.3.2"
                  , "retry-0.9.1.0"
                  , "rfc5051-0.2"
                  , "rio-0.1.21.0"
                  , "rio-prettyprint-0.1.1.0"
                  , "RSA-2.4.1"
                  , "SafeSemaphore-0.10.1"
                  , "sandi-0.5"
                  , "scrypt-0.5.0"
                  , "SDL-0.6.7.0"
                  , "SDL-image-0.6.2.0"
                  , "SDL-mixer-0.6.3.0"
                  , "securemem-0.1.10"
                  , "semigroups-0.20"
                  , "setenv-0.1.1.3"
                  , "setlocale-1.0.0.10"
                  , "shakespeare-2.0.25.1"
                  , "ShellCheck-0.8.0"
                  , "show-combinators-0.2.0.0"
                  , "silently-1.2.5.2"
                  , "skein-1.0.9.4"
                  , "smallcheck-1.2.1"
                  , "stateref-0.3"
                  , "stm-chans-3.0.0.6"
                  , "store-core-0.4.4.4"
                  , "streaming-0.2.3.1"
                  , "streaming-binary-0.3.0.1"
                  , "streaming-bytestring-0.2.1"
                  , "strict-concurrency-0.2.4.3"
                  , "string-conv-0.1.2"
                  , "string-qq-0.0.4"
                  , "sundown-0.6"
                  , "system-fileio-0.3.16.4"
                  , "system-filepath-0.4.14"
                  , "systemd-2.3.0"
                  , "tabular-0.2.2.8"
                  , "tar-0.5.1.1"
                  , "tar-conduit-0.3.2"
                  , "tasty-1.3.1"
                  , "tasty-hunit-0.10.0.3"
                  , "tasty-quickcheck-0.10.2"
                  , "tasty-rerun-1.1.18"
                  , "terminal-size-0.3.2.1"
                  , "text-format-0.3.2"
                  , "text-icu-0.8.0.1"
                  , "text-manipulate-0.3.0.0"
                  , "text-zipper-0.11"
                  , "tf-random-0.5"
                  , "th-extras-0.0.0.4"
                  , "time-locale-compat-0.1.1.5"
                  , "time-units-1.0.0"
                  , "timeit-2.0"
                  , "timezone-olson-0.2.1"
                  , "timezone-series-0.1.13"
                  , "tls-session-manager-0.0.4"
                  , "torrent-10000.1.1"
                  , "transformers-except-0.1.2"
                  , "uglymemo-0.1.0.1"
                  , "unbounded-delays-0.1.1.1"
                  , "unicode-0.0.1.1"
                  , "unix-bytestring-0.3.7.6"
                  , "uri-encode-1.5.0.7"
                  , "utility-ht-0.0.16"
                  , "uuid-1.3.15"
                  , "void-0.7.3"
                  , "wcwidth-0.0.2"
                  , "websockets-0.12.7.3"
                  , "wizards-1.0.3"
                  , "wl-pprint-annotated-0.1.0.1"
                  , "word-wrap-0.5"
                  , "X11-1.10.2"
                  , "X11-xft-0.3.4"
                  , "xml-hamlet-0.5.0.2"
                  , "xmonad-contrib-0.17.0"
                  , "xss-sanitize-0.3.7"
                  , "zlib-bindings-0.1.1.5"
                  , "zstd-0.1.3.0"
                  ]

checkConsistency :: MonadFail m => PackageSetConfig -> m PackageSetConfig
checkConsistency pset@PackageSetConfig {..} = do
  let corePackagesInPackageSet = Map.keysSet packageSet `Set.intersection` Map.keysSet corePackages
  unless (Set.null corePackagesInPackageSet) $
    fail ("core packages listed in package set: " <> List.intercalate ", " (unPackageName <$> Set.toList corePackagesInPackageSet))
  pure pset
