#! /usr/bin/env bash

set -eu -o pipefail

if [ $# -eq 2 ]; then
    pkg="$1"
    ver="$2"
else
    echo >&2 "Usage: $0 package-name version"
    exit 1
fi

tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/cblrpm-$pkg-$ver-XXX")
trap "rm -rf $tmpdir" 0

pushd >/dev/null $tmpdir
specdir=$(cblrpm spec "$pkg-$ver")
popd >/dev/null

rm -rf "$specdir"
mv "$tmpdir" "$specdir"
