#! /usr/bin/env bash

set -eu -o pipefail

foo()
{
  echo $#: $@
}

if [ $# -eq 0 ]; then
  echo >&2 "*** command line syntax error"
  echo >%1 "Usage: $0 non-empty commit message"
  exit 1
fi

projects=$( osc st | sed -r -e 's|^. +([^/]+)(/.+)?$|\1|' | uniq )

test -n "${projects:-}" || exit 1

echo committing: $projects
# --noservice due to https://github.com/openSUSE/obs-service-format_spec_file/issues/17
osc commit --noservice -m "$*" $projects
