#! /usr/bin/env bash

set -eu -o pipefail

pkg=$(basename $PWD)
pkg=${pkg##ghc-}
reason=$@

mkdir -p ../../../patches/common/$pkg
osc diff *.spec >../../../patches/common/$pkg/${reason// /-}.patch

echo $pkg: created ${reason// /-}.patch

osc commit --noservice -m "$reason" *.spec
