#! /usr/bin/env bash

set -eu -o pipefail
shopt -s nullglob

# Run this script in a build directory.
test -n "$(echo *.spec)"

git init -q .
{ echo "/*.changes"
  echo "/*.tar.gz"
  echo "/?.cabal"
  echo "/.osc"
} >>.git/info/exclude
git add -- *.spec
git commit -m "initial version"
