#! /usr/bin/env bash

set -eu -o pipefail

tmp="/tmp/submit-factory-update-tmp.$$"
trap "rm -f $tmp" 0

pkg="$1"

osc sr devel:languages:haskell:lts:6 "$pkg" devel:languages:haskell -m "license update" -d >"$tmp"
lines=$(wc -l "$tmp" | cut -f1 -d' ')
if [ "$lines" -gt 3 ]; then
  echo y | osc sr -m "license update" devel:languages:haskell:lts:6 "$pkg" devel:languages:haskell >"$tmp" || true
  reqid=$(sed -n -e "s/.*created request id //p" "$tmp")
  if [ -z "$reqid" ]; then
    cat "$tmp"
    exit 1
  fi
  osc rq accept -m ok "$reqid"
else
  echo "$pkg is up-to-date in devel:languages:haskell"
fi

echo y | osc sr -m "initial version" devel:languages:haskell "$pkg" openSUSE:Factory
