#! /usr/bin/env bash

set -eu -o pipefail

tmp="/tmp/sync-devel-project-into-factory"

test -f "$tmp/status" || osc prdiff --show-not-in-new devel:languages:haskell openSUSE:Factory >"$tmp/status"

new=$( sed -n -e "s/^old only:[ \t]*//p" "$tmp/status" )
changed=$( sed -n -e "s/^differs:[ \t]*//p" "$tmp/status" )

for n in $changed; do
    test -f "$tmp/$n.diff" || osc rdiff openSUSE:Factory "$n" devel:languages:haskell >"$tmp/$n.diff"
    if grep --silent -F "$n.changes" "$tmp/$n.diff"; then
        updated+=" $n"
    elif grep --silent -E "^[+-](Version|License|Source[0-9]|Patch[0-9]*):" "$tmp/$n.diff"; then
        suspicious+=" $n"
    fi
done

echo
echo "# =============== new packages ==============="
echo
for n in $new; do
    test -f "$tmp/$n.requests" || osc rq list devel:languages:haskell "$n" >"$tmp/$n.requests"
    if grep --silent -F "No results for package" "$tmp/$n.requests"; then
        echo osc sr devel:languages:haskell "$n" openSUSE:Factory
    else
        echo "# $n has been submitted already: $tmp/$n.requests"
    fi
done

echo
echo "# =============== modified packages ==============="
echo
for n in $updated; do
    test -f "$tmp/$n.requests" || osc rq list devel:languages:haskell "$n" >"$tmp/$n.requests"
    if grep --silent -F "No results for package" "$tmp/$n.requests"; then
        echo osc sr devel:languages:haskell "$n" openSUSE:Factory
    else
        echo "# $n has been submitted already: $tmp/$n.requests"
    fi
done

echo
echo "# =============== suspicious modified packages without change log ==============="
echo
echo "emacsclient "
for n in $suspicious; do
    echo -n " $tmp/$n.diff"
done
echo




##
##
## isInFactory()
## {
##   osc ls "openSUSE:Factory/$1/$1.spec" >/dev/null 2>&1
## }
##
## for i in *; do
##   # if ! isInFactory $i; then
##   #   continue
##   # fi
##
##   # Make sure we're looking only at Haskell packages checked into OBS.
##   test -d "$i" || continue
##   test -d "$i/.osc" || continue
##   if ! grep --silent ghc-rpm-macros "$i/$i.spec"; then
##    test -z "${DEBUG:-}" || echo >&2 "$i: skip non-Haskell package"
##    continue
##   fi
##
##   # Diff the current package against devel:languages:haskell and check whether
##   # the changes are significant.
##   if [ ! -e "$HOME/src/obs/haskell/$i/$i.spec" ]; then
##     test -z "${DEBUG:-}" || echo >&2 "$i: new submission"
##     echo "$i"
##     continue
##   fi
##   diff -ub "$HOME/src/obs/haskell/$i/$i.spec" "$i/$i.spec" >"$tmp" || true
##   lines=$(wc -l "$tmp" | cut -f1 -d' ')
##   if [ "$lines" -gt 3 ]; then
##       if isChangeSignificant "$tmp"; then
##           echo "$i"
##       else
##         test -z "${DEBUG:-}" || echo >&2 "$i: no significant changes"
##       fi
##   else
##     test -z "${DEBUG:-}" || echo >&2 "$i: no changes"
##   fi
## done
